name: Filestash
options:
  bundleIdPrefix: app.filestash
  deploymentTarget:
    macOS: "13.0"
  createIntermediateGroups: true
settings:
  base:
    SWIFT_VERSION: "5.9"
targets:
  Filestash:
    type: application
    platform: macOS
    sources:
      - App
      - Shared
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: app.filestash.mac
    info:
      path: App/Info.plist
      properties:
        CFBundleDisplayName: Filestash
        LSUIElement: true
